Add `@latest` release tag, improve README consistency
miroapp/app-examples pull request #63
Opened 2022-05-18 12:07 UTC by marcospinello

- Add `@latest` release tag to install the sample app
- Improve README consistency across sample app README files

2022-05-18 12:20 UTC, bishopwm submitted a review, later dismissed

2022-05-18 12:49 UTC, ahmedelgabri requested changes
@marcospinello can you please remove the `package-lock.json` file, it's not needed since the repo uses `yarn` & had `yarn.lock` file already.

2022-05-18 12:50 UTC, ahmedelgabri commented on package.json
> -    "husky": "^7.0.0",
@marcospinello Any reason why this change was made?

2022-05-19 08:26 UTC, ahmedelgabri approved these changes

2022-05-19 08:27 UTC, ahmedelgabri commented on yarn.lock
> +vite@2.7.13:
@addisonschultz I think we sometimes merge PRs without running `yarn` on them which makes `yarn.lock` file out of sync & that's why these changes appear randomly in other PRs.

2022-05-19 13:53 UTC, addisonschultz approved these changes

2022-05-19 13:54 UTC, merged